# Generated by Django 4.2.1 on 2023-09-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=80)),
                ('full_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.ImageField(upload_to='')),
                ('time', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client')),
            ],
        ),
    ]
