# Generated by Django 4.2.1 on 2023-06-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_category',
        ),
        migrations.AlterField(
            model_name='issue',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.device'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
