# Generated by Django 4.2.1 on 2023-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_news_issue_count_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_type',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/services/img/'),
        ),
    ]
