# Generated by Django 4.2.1 on 2023-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_feedback_image_alter_feedback_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='resource',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
