# Generated by Django 4.2.7 on 2023-11-15 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_news_full_text_alter_news_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerChangeTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milliseconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)])),
            ],
        ),
    ]
